# Generated by Django 5.2.7 on 2025-10-15 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobby.activegames')),
            ],
        ),
    ]
