# Generated by Django 5.2.7 on 2025-10-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
