# Generated by Django 5.2.7 on 2025-10-16 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatSystem', '0002_alter_messages_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='game_id',
            new_name='game',
        ),
    ]
