# Generated by Django 5.2.7 on 2025-10-19 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatSystem', '0004_alter_messages_message'),
        ('players', '0004_alter_cards_type_alter_cards_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='author',
            field=models.ForeignKey(default='System', on_delete=django.db.models.deletion.CASCADE, to='players.players'),
        ),
    ]
