# Generated by Django 5.2.7 on 2025-10-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activegames',
            name='num_of_players',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activegames',
            name='solution_character',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activegames',
            name='solution_room',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activegames',
            name='solution_weapon',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
