# Generated by Django 5.2.7 on 2025-10-15 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0002_activegames_num_of_players_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activegames',
            old_name='game_id',
            new_name='id',
        ),
    ]
