# Generated by Django 5.2.7 on 2025-10-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0003_rename_game_id_activegames_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activegames',
            name='solution_character',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='activegames',
            name='solution_room',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='activegames',
            name='solution_weapon',
            field=models.CharField(max_length=100),
        ),
    ]
