# Generated by Django 5.2.7 on 2025-10-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0004_alter_activegames_solution_character_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activegames',
            name='playerPositions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activegames',
            name='turnNumber',
            field=models.BigIntegerField(blank=True, default=1),
        ),
    ]
