# Generated by Django 5.2.7 on 2025-10-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0005_activegames_playerpositions_activegames_turnnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='activegames',
            name='game_started',
            field=models.BooleanField(default=False),
        ),
    ]
