# Generated by Django 5.2.7 on 2025-11-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0006_activegames_game_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='activegames',
            name='votes_to_start',
            field=models.IntegerField(default=0),
        ),
    ]
