# Generated by Django 5.2.7 on 2025-10-15 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('character', models.CharField()),
                ('user_name', models.CharField()),
                ('out_of_game', models.BooleanField()),
                ('is_players_turn', models.BooleanField()),
                ('player_number', models.IntegerField()),
                ('current_position', models.CharField()),
                ('note_pad', models.JSONField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobby.activegames')),
            ],
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('value', models.CharField(editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(editable=False)),
                ('players_holding', models.ManyToManyField(to='players.players')),
            ],
        ),
    ]
