# Generated by Django 5.2.7 on 2025-10-15 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='user_name',
        ),
    ]
