# Generated by Django 5.2.7 on 2025-10-15 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_remove_players_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='game_id',
            new_name='game',
        ),
    ]
