# Generated by Django 5.2.7 on 2025-10-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_rename_game_id_players_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='type',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='cards',
            name='value',
            field=models.CharField(editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='players',
            name='character',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='players',
            name='current_position',
            field=models.CharField(max_length=100),
        ),
    ]
