# Generated by Django 5.2.7 on 2025-10-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_alter_cards_type_alter_cards_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='moved_by_sugg',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='players',
            name='current_position',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='is_players_turn',
            field=models.BooleanField(default=False),
        ),
    ]
